name: sponsor ❤️
on: 
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 defaults
        uses: devlooped/actions-bot@v1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🤘 checkout
        uses: actions/checkout@v2
        with: 
          token: ${{ env.GH_TOKEN }}
          
      - name: ❤️ sponsor 
        uses: devlooped/actions-sponsor@main
        with:
          token: ${{ env.GH_TOKEN }}
